version: '3.8'

services:

  frontend:
    container_name: flashbackfiesta-frontend
    image: ghcr.io/trullfax/flashbackfiesta-frontend:main
    pull_policy: always
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
