version: '3.8'

services:

  frontend:
    container_name: flashbackfiesta-frontend
    image: ghcr.io/trullfax/flashbackfiesta-frontend:main
    pull_policy: always
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    environment:
      PUBLIC_SUPABASE_URL: ${PUBLIC_SUPABASE_URL}
      PUBLIC_SUPABASE_KEY: ${PUBLIC_SUPABASE_KEY}
      SERVICE_ROLE_KEY: ${SERVICE_ROLE_KEY}
      TMDB_SECRET_API_KEY: ${TMDB_SECRET_API_KEY}
    ports:
      - "3000:3000"
