version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SUPABASE_URL: ${SUPABASE_URL}
        SUPABASE_KEY: ${SUPABASE_KEY}
    ports:
      - "3000:3000"
    env_file:
      - .env