version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SUPABASE_URL: ${SUPABASE_URL}
        SUPABASE_KEY: ${SUPABASE_KEY}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    env_file:
      - .env

volumes:
  node_modules: