# Stage 1: Build the application
FROM node:22-alpine AS builder
WORKDIR /app

# Define build-time arguments
ARG SUPABASE_URL
ARG SUPABASE_KEY

# Set environment variables
ENV SUPABASE_URL=$SUPABASE_URL
ENV SUPABASE_KEY=$SUPABASE_KEY

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build
RUN npm ci --prod

# Stage 2: Create the runtime image
FROM node:22-alpine
USER node:node
WORKDIR /app

# Define runtime arguments
ARG SUPABASE_URL
ARG SUPABASE_KEY

# Set environment variables again for runtime
ENV SUPABASE_URL=$SUPABASE_URL
ENV SUPABASE_KEY=$SUPABASE_KEY

COPY --from=builder --chown=node:node /app/build ./build
COPY --from=builder --chown=node:node /app/node_modules ./node_modules
COPY --chown=node:node package.json .
CMD ["node", "build"]
