name: Build and Publish image to Docker Hub

on: [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Registry
        run: |
          docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: build image
        run: |
          IMAGE_ID="${{ secrets.DOCKER_HUB_USERNAME }}/flashbackfiesta-webapp:latest"
          docker build ./webapp/ \
            --build-arg VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }} \
            --build-arg VITE_SUPABASE_KEY=${{ secrets.VITE_SUPABASE_KEY }} \
            --build-arg SERVICE_ROLE_KEY=${{ secrets.SERVICE_ROLE_KEY }} \
            --build-arg TMDB_SECRET_API_KEY=${{ secrets.TMDB_SECRET_API_KEY }} \
            -t $IMAGE_ID .

      - name: Push Docker Image to Registry
        run: |
          docker push $IMAGE_ID
