name: Deploy Supabase Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.FLASHBACKFIESTA_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 22 -t ed25519 ${{ secrets.FLASHBACKFIESTA_HOST }} >> ~/.ssh/known_hosts

 #     - name: Start SSH agent and add key
 #       run: |
 #         # Start ssh-agent
 #         eval "$(ssh-agent -s)"
 #         # Use the passphrase directly
 #         echo "${{ secrets.SSH_KEY_PASSPHRASE }}" | ssh-add ~/.ssh/id_ed25519

      - name: Debug SSH Authentication
        run: |
          ssh -i ~/.ssh/id_ed25519 -p 22 ${{ secrets.FLASHBACKFIESTA_USERNAME }}@${{ secrets.FLASHBACKFIESTA_HOST }} 'echo "SSH Authentication successful"'


      - name: Deploy Supabase functions
        run: |
          rsync -azP -e "ssh -i ~/.ssh/id_ed25519 -p 22" ./supabase/functions/ ${{ secrets.FLASHBACKFIESTA_USERNAME }}@${{ secrets.FLASHBACKFIESTA_HOST }}:~/supabase/docker/volumes/functions --verbose

      - name: Restart Supabase services
        run: |
          ssh -i ~/.ssh/id_ed25519 -p 22 ${{ secrets.FLASHBACKFIESTA_USERNAME }}@${{ secrets.FLASHBACKFIESTA_HOST }} 'docker compose up -d ~/supabase/docker/docker-compose.yml restart functions'
