name: Build and Publish image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  publish_image:
    runs-on: ubuntu-latest
    env:
      IMAGE_ID: "${{ secrets.DOCKER_HUB_USERNAME }}/flashbackfiesta-webapp:${{ github.sha }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Registry
        run: |
          docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" -p "${{ secrets.DOCKER_HUB_TOKEN }}"

      - name: Build Docker Image
        run: |
          docker buildx build ./webapp/ \
            --build-arg VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }} \
            --build-arg VITE_SUPABASE_KEY=${{ secrets.VITE_SUPABASE_KEY }} \
            --build-arg SERVICE_ROLE_KEY=${{ secrets.SERVICE_ROLE_KEY }} \
            --build-arg TMDB_SECRET_API_KEY=${{ secrets.TMDB_SECRET_API_KEY }} \
            -t ${{ env.IMAGE_ID }}

      - name: Push Docker Image to Registry
        run: |
          docker push ${{ env.IMAGE_ID }}

      - name: Set up SSH key
        run: |
          set -e
          mkdir -p ~/.ssh
          echo "${{ secrets.FLASHBACKFIESTA_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 22 -t ed25519 ${{ secrets.FLASHBACKFIESTA_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          set -e
          docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" -p "${{ secrets.DOCKER_HUB_TOKEN }}"
          ssh -i ~/.ssh/id_ed25519 -p 22 ${{ secrets.FLASHBACKFIESTA_USERNAME }}@${{ secrets.FLASHBACKFIESTA_HOST }} << EOF
            docker pull ${{ env.IMAGE_ID }}
            docker stop flashbackfiesta-webapp || true
            docker rm flashbackfiesta-webapp || true
            docker run -d --name flashbackfiesta-webapp \
              -e VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }} \
              -e VITE_SUPABASE_KEY=${{ secrets.VITE_SUPABASE_KEY }} \
              -e SERVICE_ROLE_KEY=${{ secrets.SERVICE_ROLE_KEY }} \
              -e TMDB_SECRET_API_KEY=${{ secrets.TMDB_SECRET_API_KEY }} \
              -p 3000:3000 ${{ env.IMAGE_ID }}
          EOF
